### ISSUE TITLE
panic: runtime error: index out of range [233] with length 233

### ISSUE THREAD

**Issue by fryorcraken** [status-im/status-desktop#10490]
# Bug Report

## Description

Segmentation fault.

## Steps to reproduce

Unsure, I was AFK when it happened

#### Expected behavior

No crash

#### Actual behavior

Yes crash

### Additional Information

- Status desktop version: v0.11.0
- Operating System: Fedora Linux

```
panic: runtime error: index out of range [233] with length 233

goroutine 28151565 [running]:
github.com/status-im/status-go/services/wallet/token.(*Manager).GetBalancesByChain.func3({0x7f05a81b0f80?, 0x1c0346d1080?})
	/home/jenkins/workspace/status-desktop/platforms/linux/x86_64/vendor/status-go/services/wallet/token/token.go:709 +0x445
github.com/status-im/status-go/services/wallet/async.(*AtomicGroup).Add.func1()
	/home/jenkins/workspace/status-desktop/platforms/linux/x86_64/vendor/status-go/services/wallet/async/async.go:114 +0x68
created by github.com/status-im/status-go/services/wallet/async.(*AtomicGroup).Add
	/home/jenkins/workspace/status-desktop/platforms/linux/x86_64/vendor/status-go/services/wallet/async/async.go:112 +0x8d
[1]    8831 segmentation fault (core dumped)  ~/.local/bin/StatusIm-Desktop-v0.11.0-621f0c-x86_64.AppImage
```

Full logs: [segfault_status_desktop.txt](https://github.com/status-im/status-desktop/files/11363801/segfault_status_desktop.txt)

**Comment by iurimatias** [comment]
@fryorcraken what version of the app?

**Comment by jrainville** [comment]
> Status desktop version: v0.11.0

**Comment by alaibe** [comment]
See this PR: https://github.com/status-im/status-go/pull/3446
Curiously, i don't understand how that is possible :thinking:
