### ISSUE TITLE
[release 0.12.0] non-Go code set up signal handler without SA_ONSTACK flag when adding account in wallet

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#10608]
### Description

1. install app https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.12.x/4/
2. enable biometrics
3. open wallet
4. click Add account and confirm action with fingerprint

```
ERR 2023-05-10 10:41:32.171+03:00 sm_cannot resolve current state            topics="app-controller" tid=430094 file=module.nim:136
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x105df83ca?, 0x14000104480?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x1400005a790 sp=0x1400005a760 pc=0x105cbd5c0
runtime.sigNotOnStack(0x10)
	/usr/local/go/src/runtime/signal_unix.go:1029 +0x5c fp=0x1400005a7b0 sp=0x1400005a790 pc=0x105cd38ec
runtime.adjustSignalStack(0x10, 0x1400004c000, 0x1400005a858)
	/usr/local/go/src/runtime/signal_unix.go:581 +0x250 fp=0x1400005a820 sp=0x1400005a7b0 pc=0x105cd2c20
runtime.sigtrampgo(0x10, 0x1400005a9c0, 0x1400005aa28)
	/usr/local/go/src/runtime/signal_unix.go:469 +0x170 fp=0x1400005a8a0 sp=0x1400005a820 pc=0x105cd2870
runtime.sigtrampgo(0x10, 0x1400005a9c0, 0x1400005aa28)
	<autogenerated>:1 +0x1c fp=0x1400005a8d0 sp=0x1400005a8a0 pc=0x105ceeb7c
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_darwin_arm64.s:227 +0x4c fp=0x1400005a990 sp=0x1400005a8d0 pc=0x105cedd5c

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000056fe0 sp=0x14000056fe0 pc=0x105cecca4

goroutine 17 [running, locked to thread]:
	goroutine running on other thread; stack unavailable

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000048fa0 sp=0x14000048f80 pc=0x105cbff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0x14000048fd0 sp=0x14000048fa0 pc=0x105cbfde0
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000048fd0 sp=0x14000048fd0 pc=0x105cecca4
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000049760 sp=0x14000049740 pc=0x105cbff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:278 +0x98 fp=0x140000497b0 sp=0x14000049760 pc=0x105cadae8
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x140000497d0 sp=0x140000497b0 pc=0x105ca2b48
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000497d0 sp=0x140000497d0 pc=0x105cecca4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x14000070000?, 0x105e3c398?, 0x1?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000049f50 sp=0x14000049f30 pc=0x105cbff90
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x105f8d800)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x5c fp=0x14000049f80 sp=0x14000049f50 pc=0x105caba1c
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:628 +0x44 fp=0x14000049fb0 sp=0x14000049f80 pc=0x105cabf74
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x14000049fd0 sp=0x14000049fb0 pc=0x105ca2ae8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000049fd0 sp=0x14000049fd0 pc=0x105cecca4
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x140000485a8?, 0x105c97f30?, 0x40?, 0x30?, 0x1037e8a90?)
	/usr/local/go/src/runtime/proc.go:381 +0xe0 fp=0x14000048580 sp=0x14000048560 pc=0x105cbff90
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x100 fp=0x140000487d0 sp=0x14000048580 pc=0x105ca1c10
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000487d0 sp=0x140000487d0 pc=0x105cecca4
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x80
Traceback (most recent call last)
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(197) nim_status_client
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(194) mainProc
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(559) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app_service/service/keychain/service.nim(67) onKeychainManagerSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/eventemitter.nim(58) emit
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(147) :anonymous
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/io_interface.nim(187) keychainObtainedDataSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/module.nim(624) keychainObtainedDataSuccess
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(575) terminateCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/modules/shared_modules/keycard_popup/controller.nim(447) cancelCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app_service/service/keycard/service.nim(146) cancelCurrentFlow
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nim-keycard-go/keycard_go.nim(21) keycardCancelFlow
SIGABRT: Abnormal termination.
```

**Comment by anastasiyaig** [comment]
per Sale this should be fixed by switching to Go-1.20.4, or commit ffa200f32dece7472e2d9a9584e172804c991d05

@iurimatias @alaibe please make the adjustments needed

**Comment by alaibe** [comment]
This commit is in the release, so there is something else going on

**Comment by caybro** [comment]
@alexjba does this ring a bell? (esp. the part with `fatal error: non-Go code set up signal handler without SA_ONSTACK flag`)

**Comment by bitgamma** [comment]
to give some context, the signal is not being raised by the keycard library or by the pcsc library. Signal 16 (on darwin) is used internally by the go runtime as a preemption signal, to switch the active routine. Because of a bug specific to aarch64 the stack pointer could end up in a area outside the expected range, causing this fatal error.

The issue has been fixed in go 1.20.4 and @saledjenic's local build works fine, so the next step would be to find out what is the difference between what is being built locally and CI's build

**Comment by alexjba** [comment]
I guess we need to revisit this: https://github.com/status-im/status-desktop/blob/a57c0b414bd52b39ce6e0060280ba5e3cd444f4a/src/nim_status_client.nim#LL91C20-L91C20

Adding `SA_ONSTACK` might fix the issue as `go` docs says:
```
If the non-Go code installs any signal handlers, it must use the SA_ONSTACK flag with sigaction. Failing to do so is likely to cause the program to crash if the signal is received. Go programs routinely run with a limited stack, and therefore set up an alternate signal stack.
```

Signal 16 seems to be `{16, "SIGURG", "urgent I/O condition"}` and might signal a bug in the app, but I don't think it should crash the app.

```
SIGURG (Urgent I/O condition)
          This signal is generated when an ``urgent condition'' exists on a
          socket.  In practice this means when [tcp(4)](https://man.netbsd.org/tcp.4) out-of-band data has
          arrived.  The default action is to do nothing.  The number for
          SIGURG is 16.
```

**Comment by anastasiyaig** [comment]
@jakubgs can u please update go version everywhere in CI (pr builds, master build, release builds) to `1.20.4`?

**Comment by jakubgs** [comment]
All CI hosts are using the new Go version. Are you sure you didn't just forget to cherry pick the upgrade commit for the release?
```
 > a ci-slave-linux -o -a 'go version'
linux-04.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-06.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-05.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-02.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-03.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-01.he-eu-hel1.ci.release | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
linux-01.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 linux/amd64
```

**Comment by anastasiyaig** [comment]
@iurimatias please check the version of go in release, or @alaibe

**Comment by alaibe** [comment]
@jakubgs I can see the commit is in the release: https://github.com/status-im/status-desktop/commits/release/0.12.x?after=dd1c30b92835309c120e886aeb72e58f64ab7908+34&branch=release%2F0.12.x&qualified_name=refs%2Fheads%2Frelease%2F0.12.x

only linux build? they also make the build for mac os?

**Comment by jakubgs** [comment]
Indeed, it looks like the release Windows CI host was not upgraded.
```
 > a ci-slave-windows -m win_shell -o -a 'go version'
windows-01.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 windows/amd64
windows-02.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 windows/amd64
windows-01.he-eu-hel1.ci.release | CHANGED | rc=0 | (stdout) go version go1.19.8 windows/amd64
```
```
maci7-01.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/amd64
maci7-02.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/amd64
maci7-03.ms-eu-dublin.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/amd64
macm1-01.ih-eu-mda1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/arm64
macm1-01.he-eu-fsn1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/arm64
macm1-02.he-eu-fsn1.ci.devel | CHANGED | rc=0 | (stdout) go version go1.20.4 darwin/arm64

```
But Macs are all upgraded. Is this issue regarding Windows? I don't see anything about the OS in the description.

**Comment by jakubgs** [comment]
Fixed:
```
admin@windows-01 MINGW64 ~
$ go version
go version go1.20.4 windows/amd64
```

**Comment by anastasiyaig** [comment]
@jakubgs the inital problem to me is on m1 mac

**Comment by jakubgs** [comment]
Well, you can see the Go version on M1 macs above. They are all `1.20.4`.

**Comment by anastasiyaig** [comment]
since @dlipicar does not see the issue , it could be something happening to me only. Lets downgrade this and i will try to investigate more

**Comment by anastasiyaig** [comment]
Okay, apparently i was using terminal under x86 and when i switched to m1 i dont see the problem.
