### ISSUE TITLE
Error failed to compute offset when launching the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#12691]
### Description

**Satus version:** 0.15 rc1 https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.15.x/2/

1. I opened app and recovered my account
2. I closed the app and enabled VPN
3. I opened app again (started in terminal) and it is not launching anymore
4. I switched off VPN and tried one more time, no luck, app is not starting

Geth.log: [geth.log](https://github.com/status-im/status-desktop/files/13319337/geth.log)

```
ERROR[11-10|15:24:13.567] failed to compute offset                 error="RPC failed: read udp 10.10.0.50:57314->17.253.28.253:123: i/o timeout; read udp 10.10.0.50:54718->162.159.200.1:123: i/o timeout; read udp 10.10.0.50:50802->5.196.160.139:123: i/o timeout; read udp 10.10.0.50:60725->82.64.247.11:123: i/o timeout; read udp 10.10.0.50:62479->5.196.160.139:123: i/o timeout; read udp 10.10.0.50:63948->20.101.57.9:123: i/o timeout; read udp 10.10.0.50:54635->133.243.238.244:123: i/o timeout; read udp 10.10.0.50:56351->202.118.1.46:123: i/o timeout."
failed to compute offset
```

I waited a bit for the app to kill itself and this is the additional log shown:

```
panic: sync: negative WaitGroup counter

goroutine 31 [running]:
sync.(*WaitGroup).Add(0xc14ba7227b465100?, 0x1d14cdb024?)
	/usr/local/go/src/sync/waitgroup.go:62 +0x108
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:87
github.com/status-im/status-go/timesource.(*NTPTimeSource).updateOffset(0x240000debd0)
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/timesource/timesource.go:202 +0x2c8
github.com/status-im/status-go/timesource.(*NTPTimeSource).runPeriodically.func1()
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/timesource/timesource.go:235 +0x88
created by github.com/status-im/status-go/timesource.(*NTPTimeSource).runPeriodically
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/timesource/timesource.go:231 +0xe8
SIGABRT: Abnormal termination.
```

**Comment by anastasiyaig** [comment]
@jrainville i guess it could be related to waku but not sure. I asked in the waku server in discord, will post here if i hear more news but meanwhile perhaps u can reach out to Richard to check?

**Comment by anastasiyaig** [comment]
UPD: seems @richard-ramos was able to reproduce

**Comment by richard-ramos** [comment]
I believe the problem is that VPN might not have support for UDP. I tried to reproduce it with a diff one and did not run into the issue, however If i disconnect my machine completely and try to login, I see the same error reported. 

The problem seems to happen here: 
https://github.com/status-im/status-go/blob/develop/timesource/timesource.go#L276-L289

If I print some lines like this:
```go
func GetCurrentTime() (*time.Time, error) {
        fmt.Println("GetCurrentTime - Start :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
	ts := Default()
	if err := ts.Start(); err != nil {
                fmt.Println("GetCurrentTime - Failure1 :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
		return nil, err
	}
	var t *time.Time
	ts.AddCallback(func(now time.Time) {
		t = &now
	}).Wait()
	if ts.updatedOffset {
                fmt.Println("GetCurrentTime - Success :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
		return t, nil
	}
        fmt.Println("GetCurrentTime - Failure2 :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::")
	return nil, errUpdateOffset
}
```

I end up with the following output, with status-go freezing in the second `GetCurrentTime - Start`
```
INFO [11-10|09:15:16.028] Status backend initialized               backend=geth version=0.171.12 commit=ad95327e5 IpfsGatewayURL=https://ipfs.status.im/
GetCurrentTime - Start :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
ERROR[11-10|09:15:16.031] failed to compute offset                 error="RPC failed: dial udp 61.205.120.130:123: connect: network is unreachable; dial udp 202.118.1.47:123: connect: network is unreachable; lookup amazon.pool.ntp.org: no such host; lookup android.pool.ntp.org: no such host; lookup pool.ntp.org: no such host; lookup time.windows.com: no such host; lookup time.cloudflare.com: no such host; lookup time.apple.com: no such host."
GetCurrentTime - Failure1 :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
failed to compute offset
Warning: QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future. (:0, )
INF 2023-11-10 09:15:16.190-04:00 Version: 7e9020c19                         topics="status-app" tid=290088 file=nim_status_client.nim:197
INF 2023-11-10 09:15:16.191-04:00 Commit: 7e9020c19                          topics="status-app" tid=290088 file=nim_status_client.nim:198
INF 2023-11-10 09:15:16.191-04:00 Current date:                              topics="status-app" tid=290088 file=nim_status_client.nim:199 currentDateTime=2023-11-10T09:15:16-04:00
INF 2023-11-10 09:15:16.191-04:00 starting application controller...         topics="status-app" tid=290088 file=nim_status_client.nim:201
DBG 2023-11-10 09:15:16.191-04:00 init keycard using                         topics="keycard-service" tid=290088 file=service.nim:84 pairingsJson=/home/richard/status/status-desktop/Status/data/keycard/pairings.json
DBG 2023-11-10 09:15:16.191-04:00 initialization response:                   topics="keycard-service" tid=290088 file=service.nim:87 initResp=ok
GetCurrentTime - Start :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by richard-ramos** [comment]
> @jrainville i guess it could be related to waku but not sure. I asked in the waku server in discord, will post here if i hear more news but meanwhile perhaps u can reach out to Richard to check?

Also, not related to waku :) i originally thought it was because we do have ntp functionality there but this is in status-go

**Comment by anastasiyaig** [comment]
Perfect , thanks for investigation @richard-ramos ❤️

**Comment by osmaczko** [comment]
Can reproduce as well, thanks @richard-ramos for initial investigation. It seems there is a deadlock in timesource impl.
