### ISSUE TITLE
panic: interface conversion: interface {} is nil, not int64

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#14494]
### Description

No clear steps for now. I recovered account, opened settings, then i saw there is recovered keypair in the list of keypairs which was marked with yellow font saying that i need to prove that this keypair is mine. I clicked to delete this keypair and then application crashed

```
panic: interface conversion: interface {} is nil, not int64

goroutine 2065 [running]:
github.com/status-im/status-go/services/wallet.(*Reader).startWalletEventsWatcher.func1({{0x109d96f9c, 0x19}, 0x0, {0x1400a982450, 0x1, 0x1}, {0x0, 0x0}, 0x6621057c, 0xaa36a7, ...})
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/services/wallet/reader.go:225 +0x19c
github.com/status-im/status-go/services/wallet/walletevent.watch({0x10aa7de98, 0x140007381e0}, 0x14000252510?, 0x14003320fa0)
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/services/wallet/walletevent/watcher.go:61 +0x1a0
github.com/status-im/status-go/services/wallet/walletevent.(*Watcher).Start.func1({0x10aa7de98?, 0x140007381e0?})
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/services/wallet/walletevent/watcher.go:34 +0x30
github.com/status-im/status-go/services/wallet/async.(*Group).Add.func1()
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/services/wallet/async/async.go:107 +0x34
created by github.com/status-im/status-go/services/wallet/async.(*Group).Add
	/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/status-go/services/wallet/async/async.go:106 +0x88
SIGABRT: Abnormal termination.
zsh: abort      ./nim_status_client --datadir=~/data/Master1 --LOG_LEVEL=DEBUG
anastasiya@Anastasiyas-MacBook-Pro MacOS % 
```

**Comment by anastasiyaig** [comment]
@caybro i am running the CI build , so local go should not matter

**Comment by anastasiyaig** [comment]
should be fixed
