### ISSUE TITLE
panic: runtime error: slice bounds out of range [2:0] - onboarding with locked keycard crashes the app

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#16865]
### Description

1. lock keycard
2. start the app (clean db)
3. insert reader and keycard
4. select I already use status
5. select I dont have other device
6. select Login with keycard
7. unlock keycard with seed
8. set pin

**Result:** app crashes when user clicks I want to use PIN on the next screen (asking how to authenticate transactions)

```
DBG 2024-12-04 12:24:42.422Z keycardStartFlow                           topics="keycard-service" tid=39061689 file=service.nim:168 kcServiceCurrFlow=GetMetadata payload={} response=ok
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
DBG 2024-12-04 12:24:42.683Z keycard_signal                             topics="keycard-service" tid=39061689 file=service.nim:118 response="{\"type\":\"keycard.flow-result\",\"event\":{\"card-metadata\":{\"name\":\"keycard\",\"wallets\":[{\"path\":\"m/44'/60'/0'/0/0\",\"publicKey\":\"\"},{\"path\":\"m/44'/60'/0'/0/1\",\"publicKey\":\"\"}]},\"instance-uid\":\"34e53fc31261f02577db42505d1be3d4\",\"key-uid\":\"1292e6b5d6cf15e13ca1ddb448316b3fa26706033f7b419bbfab3252c1ee3176\"}}"
DBG 2024-12-04 12:24:42.684Z on_keycard_response                        topics="app-controller" tid=39061689 file=module.nim:460 currFlow=FirstRunOldUserKeycardImport currState=KeycardRepeatPin
DBG 2024-12-04 12:24:42.885Z keycardCancelFlow                          topics="keycard-service" tid=39061689 file=service.nim:189 kcServiceCurrFlow=NoFlow response="cannot cancel idle flow"
DBG 2024-12-04 12:24:42.887Z keycardStartFlow                           topics="keycard-service" tid=39061689 file=service.nim:168 kcServiceCurrFlow=LoadAccount payload="{\"mnemonic\":\"wolf finish toilet depth holiday flat will auction random similar toddler gospel\",\"mnemonic-length\":12,\"new-puk\":\"747402780801\",\"pin\":\"111111\",\"new-pin\":\"111111\",\"factory reset\":true}" response=ok
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
DBG 2024-12-04 12:24:45.841Z keycard_signal                             topics="keycard-service" tid=39061689 file=service.nim:118 response="{\"type\":\"keycard.flow-result\",\"event\":{\"instance-uid\":\"de07ecbb44d8b84bff93cf6fba63b22a\",\"key-uid\":\"1292e6b5d6cf15e13ca1ddb448316b3fa26706033f7b419bbfab3252c1ee3176\"}}"
DBG 2024-12-04 12:24:45.841Z on_keycard_response                        topics="app-controller" tid=39061689 file=module.nim:460 currFlow=FirstRunOldUserKeycardImport currState=KeycardRepeatPin
DBG 2024-12-04 12:24:46.042Z keycardCancelFlow                          topics="keycard-service" tid=39061689 file=service.nim:189 kcServiceCurrFlow=NoFlow response="cannot cancel idle flow"
DBG 2024-12-04 12:24:46.043Z keycardStartFlow                           topics="keycard-service" tid=39061689 file=service.nim:168 kcServiceCurrFlow=StoreMetadata payload="{\"pin\":\"111111\",\"card-name\":\"keycard\",\"wallet-paths\":[\"m/44'/60'/0'/0/0\",\"m/44'/60'/0'/0/1\"]}" response=ok
keycard - listing readers
keycard - waiting for card
keycard - card found at index 0
keycard - using reader ACS ACR39U ICC Reader
keycard - card protocol T1
DBG 2024-12-04 12:24:46.917Z keycard_signal                             topics="keycard-service" tid=39061689 file=service.nim:118 response="{\"type\":\"keycard.flow-result\",\"event\":{\"instance-uid\":\"de07ecbb44d8b84bff93cf6fba63b22a\",\"key-uid\":\"1292e6b5d6cf15e13ca1ddb448316b3fa26706033f7b419bbfab3252c1ee3176\"}}"
DBG 2024-12-04 12:24:46.918Z on_keycard_response                        topics="app-controller" tid=39061689 file=module.nim:460 currFlow=FirstRunOldUserKeycardImport currState=KeycardRepeatPin
DBG 2024-12-04 12:24:46.928Z on_keycard_response - set state            topics="app-controller" tid=39061689 file=module.nim:465 setCurrFlow=FirstRunOldUserKeycardImport setCurrState=KeycardPinSet
DBG 2024-12-04 12:24:46.932Z [threadpool task thread] initiating task   topics="task-threadpool" tid=39061706 file=threadpool.nim:56 messageType=AsyncAddCentralizedMetricIfEnabledTaskArg:ObjectType threadid=39061706 task="{\"$type\":\"AsyncAddCentralizedMetricIfEnabledTaskArg:ObjectType\",\"eventName\":\"navigation\",\"eventValueJson\":\"{\\\"viewId\\\":\\\"KeycardPinSet\\\",\\\"flowType\\\":\\\"FirstRunOldUserKeycardImport\\\"}\",\"vptr\":105553142700896,\"slot\":\"onCentralizedMetricAddedIdEnabled\"}"
DBG 2024-12-04 12:24:47.945Z primary_action                             topics="app-controller" tid=39061689 file=module.nim:198 currFlow=FirstRunOldUserKeycardImport currState=KeycardPinSet
DBG 2024-12-04 12:24:47.949Z primary_action - set state                 topics="app-controller" tid=39061689 file=module.nim:204 setCurrFlow=FirstRunOldUserKeycardImport setCurrState=Biometrics
DBG 2024-12-04 12:24:47.949Z [threadpool task thread] initiating task   topics="task-threadpool" tid=39061710 file=threadpool.nim:56 messageType=AsyncAddCentralizedMetricIfEnabledTaskArg:ObjectType threadid=39061710 task="{\"$type\":\"AsyncAddCentralizedMetricIfEnabledTaskArg:ObjectType\",\"eventName\":\"navigation\",\"eventValueJson\":\"{\\\"viewId\\\":\\\"Biometrics\\\",\\\"flowType\\\":\\\"FirstRunOldUserKeycardImport\\\"}\",\"vptr\":105553142700896,\"slot\":\"onCentralizedMetricAddedIdEnabled\"}"
DBG 2024-12-04 12:24:50.005Z secondary_action                           topics="app-controller" tid=39061689 file=module.nim:211 currFlow=FirstRunOldUserKeycardImport currState=Biometrics
DBG 2024-12-04 12:24:50.014Z Account saved succesfully                  topics="accounts-service" tid=39061689 file=service.nim:281
panic: runtime error: slice bounds out of range [2:0] [recovered]
	panic: runtime error: slice bounds out of range [2:0]

goroutine 159 [running]:
github.com/status-im/status-go/common.LogOnPanic()
	/Users/anastasiya/status-desktop/vendor/status-go/common/utils.go:104 +0x1a4
panic({0x10d800ea0?, 0x14000e04ff0?})
	/nix/store/v8llgr5prc0rawmgynacggg0q4pbvk5w-go-1.21.10/share/go/src/runtime/panic.go:914 +0x218
github.com/status-im/status-go/protocol/identity/alias.GenerateFromPublicKeyString({0x0?, 0x0?})
	/Users/anastasiya/status-desktop/vendor/status-go/protocol/identity/alias/generate.go:34 +0xe0
github.com/status-im/status-go/api.defaultSettings({0x14000052320, 0x42}, {0x0, 0x0}, 0x14b0ce0ee8?)
	/Users/anastasiya/status-desktop/vendor/status-go/api/defaults.go:69 +0x1b4
github.com/status-im/status-go/api.(*GethStatusBackend).prepareSettings(0x14000bf4180?, 0x140004a1360, 0x14000a98090)
	/Users/anastasiya/status-desktop/vendor/status-go/api/geth_backend.go:1633 +0x40
github.com/status-im/status-go/api.(*GethStatusBackend).prepareNodeAccount(0x10d589c00?, 0x140004a1360, 0x14000a98090)
	/Users/anastasiya/status-desktop/vendor/status-go/api/geth_backend.go:1507 +0x128
github.com/status-im/status-go/api.(*GethStatusBackend).RestoreKeycardAccountAndLogin(0x14000bf4180, 0x140004a1340)
	/Users/anastasiya/status-desktop/vendor/status-go/api/geth_backend.go:1397 +0x490
github.com/status-im/status-go/mobile.restoreAccountAndLogin.func1()
	/Users/anastasiya/status-desktop/vendor/status-go/mobile/status.go:598 +0x64
github.com/status-im/status-go/api.RunAsync.func1()
	/Users/anastasiya/status-desktop/vendor/status-go/api/utils.go:18 +0x4c
created by github.com/status-im/status-go/api.RunAsync in goroutine 17
	/Users/anastasiya/status-desktop/vendor/status-go/api/utils.go:16 +0x80
SIGABRT: Abnormal termination.
make: *** [run-macos] Abort trap: 6
anastasiya@MacBook-Pro status-desktop % 
```

**Comment by virginiabalducci** [comment]
Can reproduce this one on my end
[app_20241204_102505.log](https://github.com/user-attachments/files/18008948/app_20241204_102505.log)

**Comment by saledjenic** [comment]
Fixed here https://github.com/status-im/status-go/pull/6177
