### ISSUE TITLE
Language selector is empty

### ISSUE THREAD

**Issue by iurimatias** [status-im/status-desktop#7709]
# Bug Report

## Description

<img width="932" alt="Screen Shot 2022-10-02 at 8 34 15 PM" src="https://user-images.githubusercontent.com/176720/193483659-2895ed4e-b99c-40ec-ab3a-ea9d0faa1812.png">

**Comment by caybro** [comment]
![image](https://user-images.githubusercontent.com/5377645/193544533-3fcea3df-6185-426f-a8c0-9f9c1aea880d.png)

Cannot reproduce on Linux

**Comment by iurimatias** [comment]
I also cannot replicate this anymore, I think it was specific to the way I was running the build

**Comment by noeliaSD** [comment]
Well, indeed there is an issue and maybe it is related with this empty situation you saw. The app crashes when a new language is selected (not on Linux bc the call where the crash is produced is: `engine->retranslate()` on `dos_qguiapplication_load_translation` and on Linux we don't retranslate on runtime.

**Comment by osmaczko** [comment]
The crash is happening on the binding reevaluation stage, see stack trace:

```
#0  0x00007ffff671bfdd in QV4::QObjectWrapper::wrap(QV4::ExecutionEngine*, QObject*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#1  0x00007ffff670e27c in QV4::ExecutionEngine::fromVariant(QVariant const&) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#2  0x00007ffff676e826 in searchContextProperties(QV4::ExecutionEngine*, QQmlContextData*, QV4::String*, bool*, QV4::Value*, QV4::Lookup*, QV4::Lookup*, QQmlEnginePrivate*) [clone .isra.41] [clone .constprop.56]
    () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#3  0x00007ffff676f37f in QV4::QQmlContextWrapper::getPropertyAndBase(QV4::QQmlContextWrapper const*, QV4::PropertyKey, QV4::Value const*, bool*, QV4::Value*, QV4::Lookup*) ()
    at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#4  0x00007ffff676fabd in QV4::QQmlContextWrapper::resolveQmlContextPropertyLookupGetter(QV4::Lookup*, QV4::ExecutionEngine*, QV4::Value*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#5  0x00007ffff67af36c in QV4::Moth::VME::interpret(QV4::CppStackFrame*, QV4::ExecutionEngine*, char const*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#6  0x00007ffff67b36d2 in QV4::Moth::VME::exec(QV4::CppStackFrame*, QV4::ExecutionEngine*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#7  0x00007ffff674a995 in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#8  0x00007ffff68b86ea in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#9  0x00007ffff68bddf7 in QQmlBinding::evaluate(bool*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#10 0x00007ffff68c2a35 in QQmlNonbindingBinding::doUpdate(QQmlJavaScriptExpression::DeleteWatcher const&, QFlags<QQmlPropertyData::WriteFlag>, QV4::Scope&) ()
    at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#11 0x00007ffff68bf5b3 in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#12 0x00007ffff68bf87e in QQmlBinding::refresh() () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#13 0x00007ffff68635ac in QQmlContextData::refreshExpressionsRecursive(QQmlJavaScriptExpression*) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#14 0x00007ffff6863ad4 in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#15 0x00007ffff6863aa2 in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#16 0x00007ffff6863a85 in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#17 0x00007ffff6863aa2 in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#18 0x00007ffff6863aa2 in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#19 0x00007ffff6863b5e in QQmlContextData::refreshExpressionsRecursive(bool) () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#20 0x00007ffff6863c68 in QQmlContextData::refreshExpressions() () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#21 0x00007ffff684ad38 in QQmlEngine::retranslate() () at /home/osmaczny/Software/Qt/5.14.2/gcc_64/lib/libQt5Qml.so.5
#22 0x000055555657c839 in dos_qguiapplication_load_translation(DosQQmlApplicationEngine*, char const*, bool)
    (vptr=0x555556e7b460, translationPackage=0x7fffef7adba0 "/home/osmaczny/Dev/status/status-desktop/bin/i18n/qml_ar.qm", shouldRetranslate=true)
```

`QQmlEngine::retranslate()` triggers qml bindings reevaluation, so the crash can happen basically everywhere, it is caused by some faulty qml expression. Most likely some qml binding refers to the already destroyed context property (the main suspect is startup module and friends).

To identify the exact qml binding which causes the crash, qt has to be built in debug mode, otherwise [source location](https://codebrowser.dev/qt5/qtdeclarative/src/qml/qml/qqmlbinding_p.h.html#QQmlBinding::m_sourceLocation) is optimized out.

Things to try:
- ensure startup onboarding qml components are destroyed when app is loaded, so that no bindings to already destroyed startup module context property exits

Workaround:
- require all platforms to restart the app on language change and investigate the runtime language change crash as a separate task

**Comment by noeliaSD** [comment]
Workaround suggested will be applied and here the task to really solve the issue: https://github.com/status-im/status-desktop/issues/7823
