### ISSUE TITLE
panic: runtime error: slice bounds out of range [:2] with capacity 0

### ISSUE THREAD

**Issue by anastasiyaig** [status-im/status-desktop#9502]
### Description

```
panic: runtime error: slice bounds out of range [:2] with capacity 0

goroutine 358 [running]:
github.com/waku-org/go-waku/waku/v2/utils.Multiaddress(0x1c01253d290)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go:91 +0x5db
github.com/waku-org/go-waku/waku/v2/utils.EnodeToPeerInfo(0x11a8ed140?)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go:114 +0x19
github.com/waku-org/go-waku/waku/v2/discv5.evaluateNode(0x1c01253d290)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/discv5/discover.go:234 +0x3f
github.com/ethereum/go-ethereum/p2p/enode.(*filterIter).Next(0x1c001e7ca08)
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/iter.go:119 +0x54
github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).iterate(0x1c0038fe400, {0x11c284908, 0x1c0038ea900})
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:341 +0x242
github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).runPeerExchangeDiscv5Loop(0x1c0038fe400, {0x11c284908, 0x1c0038ea900})
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:386 +0x293
created by github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange.(*WakuPeerExchange).Start
	/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/status-go/vendor/github.com/waku-org/go-waku/waku/v2/protocol/peer_exchange/waku_peer_exchange.go:95 +0x1c5
```

**Comment by anastasiyaig** [comment]
@richard-ramos @0x-r4bbit hey guys, in case u are seeing this crash as well - please take a look when possible. also, please ping relevant ppl too, i am not sure that tagging you is super right thing :D

**Comment by 0x-r4bbit** [comment]
This happened to me today for the first time as well

**Comment by anastasiyaig** [comment]
@LNSD hey , sorry for pinging, is there is something u can help us to look into?

**Comment by alexandraB99** [comment]
just to say here that master seems to be working

**Comment by richard-ramos** [comment]
Looks like there is a peer somewhere with ENR record with an empty multiaddress field (even tho this field should be defined only if it has data). So when it tried to read the data from it in https://github.com/waku-org/go-waku/blob/master/waku/v2/utils/enr.go#L91, it crashed. 
The fix should be to do a:
```
if (len(multiaddrRaw) == 0) {
  return result, nil
}
```
in line 83 of that file. I can do this change in 2h

**Comment by richard-ramos** [comment]
wait why did it close?

**Comment by jrainville** [comment]
> wait, why did it close?

You put `Fixes https://github.com/status-im/status-desktop/issues/9502` in the status-go PR. That links the PR with the issue. You should have said `Needed for ...` instead

**Comment by anastasiyaig** [comment]
@jrainville @iurimatias @richard-ramos it is still crashing in RC 6 :(

**Comment by caybro** [comment]
Yup...

```go
--- vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go
+++ vendor/github.com/waku-org/go-waku/waku/v2/utils/enr.go
@@ -75,7 +75,7 @@ func Multiaddress(node *enode.Node) ([]multiaddr.Multiaddr, error) {
 	if err := node.Record().Load(enr.WithEntry(MultiaddrENRField, &multiaddrRaw)); err != nil {
 		if !enr.IsNotFound(err) {
 			return nil, err
-		} else if len(multiaddrRaw) < 2 {
+        } else if len(multiaddrRaw) < 1 {
 			// No multiaddr entry on enr
 			return result, nil
 		}
```

Fixes it

**Comment by anastasiyaig** [comment]
it was fixed and should be in master, it might just did not get merged to RC ? https://github.com/status-im/status-desktop/pull/9509
