### ISSUE TITLE
Windows CI builds do not launch

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#9758]
# Bug Report

## Description

Installing a build from CI, whether it is a PR build or a release build fails to laucnh at all with these logs:

```
$ ./Status.exe
INFO [03-06|13:50:42.001] Status backend initialized               backend=geth version=0.136.2 commit=8a296407f IpfsGatewayURL=https://ipfs.status.im/
Warning: Ignoring malformed logging rule: '*.debug=true;' (io\qloggingregistry.cpp:257, QLoggingSettingsParser::parseNextLine)
Warning: Ignoring malformed logging rule: 'qt.*.debug=false;' (io\qloggingregistry.cpp:257, QLoggingSettingsParser::parseNextLine)
Warning: Cannot open file 'C:/Users/sur_e/AppData/Local/StatusApp/status.svg', because: The system cannot find the file specified. (:0, )
Warning: Cannot open file 'C:/Users/sur_e/AppData/Local/StatusApp/status.svg', because: The system cannot find the file specified. (:0, )
INF 2023-03-06 13:50:42.285-05:00 Version: 0.9.90                            topics="status-app" tid=11812 file=nim_status_client.nim:169
INF 2023-03-06 13:50:42.285-05:00 Commit: a2a1da801                          topics="status-app" tid=11812 file=nim_status_client.nim:170
INF 2023-03-06 13:50:42.286-05:00 Current date:                              topics="status-app" tid=11812 file=nim_status_client.nim:171 currentDateTime=2023-03-06T13:50:42-05:00
INF 2023-03-06 13:50:42.287-05:00 starting application controller...         topics="status-app" tid=11812 file=nim_status_client.nim:173
Warning: QQmlApplicationEngine failed to load component (:0, )
Warning: qrc:/main.qml:317:9: Type AppMain unavailable (qrc:/main.qml:317, )
Warning: qrc:/app/mainui/AppMain.qml:1:1: module "QtQuick" version 2.15 is not installed (qrc:/app/mainui/AppMain.qml:1, )
INF 2023-03-06 13:50:43.599-05:00 starting application...                    topics="status-app" tid=11812 file=nim_status_client.nim:176
Warning: Error while loading QML: QUrl("qrc:/main.qml") (:0, )
INF 2023-03-06 13:50:43.601-05:00 shutting down...                           topics="status-app" tid=11812 file=nim_status_client.nim:144
INF 2023-03-06 13:50:43.601-05:00 logging out...                             topics="app-controller" tid=11812 file=app_controller.nim:273
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x7ffdeaac9992]

goroutine 17 [running, locked to thread]:
github.com/status-im/status-go/services/ens.(*Service).Stop(...)
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/services/ens/service.go:41
github.com/status-im/status-go/node.(*StatusNode).Cleanup(0x1c0003ae820)
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/node/status_node_services.go:604 +0x112
github.com/status-im/status-go/api.(*GethStatusBackend).cleanupServices(...)
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/api/geth_backend.go:1389
github.com/status-im/status-go/api.(*GethStatusBackend).Logout(0x1c000001860)
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/api/geth_backend.go:1359 +0xb9
github.com/status-im/status-go/mobile.Logout()
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/mobile/status.go:425 +0x25
main.Logout()
        C:/Users/jenkins/workspace/status-desktop/platforms/windows/vendor/status-go/build/bin/statusgo-lib/main.go:305 +0x19
```

0.10 works, so it's something introduced for 0.11. It seems related to the Qt upgrade:

`Warning: qrc:/app/mainui/AppMain.qml:1:1: module "QtQuick" version 2.15 is not installed (qrc:/app/mainui/AppMain.qml:1, )`

**Comment by jrainville** [comment]
@jakubgs is it possible that the Windows CI machines haven't been updated to 5.15 yet? I see `windows_build_setup.ps1` is set up to install 5.15, but we need to run it manually I think?

**Comment by jakubgs** [comment]
Yes, they have not all been upgraded yet:
```
 > a ci-slave-windows -m win_shell -a 'dir C:/Qt'
windows-01.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
    Directory: C:\Qt

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2020   2:24 PM                5.14.2
d-----        3/29/2020   3:37 PM                Docs
d-----        3/29/2020   2:24 PM                Tools

windows-02.he-eu-hel1.ci.devel | CHANGED | rc=0 >>
    Directory: C:\Qt

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/29/2020   2:24 PM                5.14.2
d-----       11/13/2020   7:02 AM                5.15.2
d-----        3/29/2020   2:24 PM                Tools
```
Since we stopped the migration process partway through due to Squish issues.

I'll run the script for `windows-01` now.

**Comment by jrainville** [comment]
Cool, thanks!

**Comment by jakubgs** [comment]
But the `windows-01` host did not have its labels updated:

![image](https://user-images.githubusercontent.com/2212681/223239293-a9e3f142-4db7-4e86-982c-e2225d65424b.png)

Which means you couldn't have hit it during a build unless you had wrong labels set in the `Jenkinsfile`.

**Comment by jakubgs** [comment]
Oh, but interestingly, on `windows-02` the `QTDIR` var has a double value:

![image](https://user-images.githubusercontent.com/2212681/223240394-65a00ed7-b455-4839-aaa7-af894946b955.png)

Which is not normal.

**Comment by jakubgs** [comment]
Looks like that's the default behavior of `win_path` Ansible task:

>New path elements are appended to the path, and existing path elements may be moved closer to the end to satisfy the requested ordering.

https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_path_module.html

**Comment by jakubgs** [comment]
For now I'll just fix it manually:

![image](https://user-images.githubusercontent.com/2212681/223241976-51012f56-4224-45dd-b206-756453788d9c.png)

But I might have to remove the var before setting it in Ansible to prevent this in the future.

**Comment by jakubgs** [comment]
We even get duplicates from multiple runs:

![image](https://user-images.githubusercontent.com/2212681/223242380-cada7b8f-7d0d-423b-ac80-ad0435ad697b.png)

**Comment by jakubgs** [comment]
Looks like I can't clear it using `win_path`:
```
TASK [status-desktop-setup : Clear VCINSTALLDIR env variable] *********************************************
fatal: [windows-01.he-eu-hel1.ci.devel]: FAILED! => {
    "changed": false
}
```
That's a pain in the ass.

**Comment by jakubgs** [comment]
Actually, there's `win_environment` that I can use:
https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_environment_module.html

Which does not deal with lists but whole values.

**Comment by jakubgs** [comment]
Fixed:

- https://github.com/status-im/infra-ci/commit/fd28225d - status-desktop-setup: fix setting QT env variables
- https://github.com/status-im/infra-ci/commit/3c3b0e13 - status-desktop-setup: trim newlines from Qt version

Looks correct now:

![image](https://user-images.githubusercontent.com/2212681/223247136-e110e349-2ace-4b70-845a-f2e354273aae.png)

All hosts should now have Qt `5.15.2` and environment variables updated correctly.
