### ISSUE TITLE
Wallet: application crashes when sending a token or just being idle for a while

### ISSUE THREAD

**Issue by saledjenic** [status-im/status-desktop#9959]
A weird crashes I've faced in the wallet section, though there are no specific steps to reproduce any of them (maybe it's a single one, but gives different logs). They occur randomly, just make sure the wallet is enabled and the app with a few wallet accounts is opened (in my case wallet was the active section) and keep the app like that (no need for any special activities there) sooner or later the app will crash.

- crash 1
```
DBG 2023-03-21 09:05:26.782+01:00 NewBE_callPrivateRPC topics="rpc" tid=947160 file=core.nim:27 rpc_method=wallet_getTransfersByAddressAndChainID 
Traceback (most recent call last) 
/Users/sale/Status/desktop-app/src/nim_status_client.nim(181) nim_status_client 
/Users/sale/Status/desktop-app/src/nim_status_client.nim(178) mainProc 
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec 
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback 
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(569) onSlotCalled
/Users/sale/Status/desktop-app/src/app_service/service/wallet_account/service.nim(633) onAllTokensBuilt
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tableimpl.nim(52) []= 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tableimpl.nim(23) rawInsert 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(147) genericSeqAssign 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(111) genericAssign 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(76) genericAssignAux 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(100) genericAssignAux 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(24) genericAssignAux 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(20) genericAssignAux 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(54) genericAssignAux 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(436) newObjNoInit 
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim(783) rawAlloc 
SIGSEGV: Illegal storage access. (Attempt to read from nil?) 
make: *** [run-macos] Error 1 
```

- crash 2
```
Traceback (most recent call last)
/Users/sale/Status/desktop-app/src/nim_status_client.nim(181) nim_status_client
/Users/sale/Status/desktop-app/src/nim_status_client.nim(178) mainProc
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/sale/Status/desktop-app/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(569) onSlotCalled
/Users/sale/Status/desktop-app/src/app_service/service/wallet_account/service.nim(640) onAllTokensBuilt
/Users/sale/Status/desktop-app/src/app/core/eventemitter.nim(57) emit
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/module.nim(143) :anonymous
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/io_interface.nim(38) refreshWalletAccounts
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/module.nim(98) refreshWalletAccounts
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim(376) map
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/module.nim(102) :anonymous
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/utils.nim(47) walletAccountToItem
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim(376) map
/Users/sale/Status/desktop-app/src/app/modules/main/wallet_section/accounts/utils.nim(47) :anonymous
/Users/sale/Status/desktop-app/src/app/modules/shared_models/token_utils.nim(27) walletTokenToItem
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/sequtils.nim(376) map
/Users/sale/Status/desktop-app/src/app/modules/shared_models/token_utils.nim(27) :anonymous
/Users/sale/Status/desktop-app/src/app/modules/shared_models/balance_utils.nim(8) balanceToItem
/Users/sale/Status/desktop-app/src/app/modules/shared_models/currency_amount_utils.nim(5) currencyAmountToItem
/Users/sale/Status/desktop-app/src/app/modules/shared_models/currency_amount.nim(25) newCurrencyAmount
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(462) newObjRC1
/Users/sale/Status/desktop-app/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim(783) rawAlloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Error 1
```

**Comment by anastasiyaig** [comment]
@alaibe i was able to see this issue today:

- open Add account and generate account with default path (dont fill anything apart account name). 
- Stay idle for a while. I was using Testnet. The app crashes with log below. 
- It also is reproducible when sending a token transaction for example (stt from main account to generated one)

```
ERR 2023-03-28 11:19:50.841+03:00 rpc response error                         topics="rpc" tid=4839207 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-03-28 11:19:50.842+03:00 error doing rpc request                    topics="rpc" tid=4839207 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-03-28 11:19:50.843+03:00 error fetchOwnedCollectiblesTaskArg:       tid=4839207 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
Traceback (most recent call last)
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/nim_status_client.nim(197) nim_status_client
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/nim_status_client.nim(194) mainProc
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(569) onSlotCalled
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/app_service/service/wallet_account/service.nim(532) onAllTokensBuilt
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/app/core/eventemitter.nim(59) emit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/app/modules/main/browser_section/current_account/module.nim(107) :anonymous
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/src/app/modules/main/browser_section/current_account/module.nim(130) onTokensRebuilt
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/tables.nim(259) []
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(147) genericSeqAssign
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(111) genericAssign
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(76) genericAssignAux
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(100) genericAssignAux
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(24) genericAssignAux
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(20) genericAssignAux
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/assign.nim(54) genericAssignAux
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(436) newObjNoInit
/Users/jenkins/workspace/s-desktop_branches_macos_PR-9820/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim(783) rawAlloc
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by stefandunca** [comment]
Not sure if unrelated but I just had a crash while authenticating to expand the "Derivation Path" section of "Add Account Popup"

```
ERR 2023-03-29 17:05:41.154+02:00 sm_cannot resolve current state            topics="app-controller" tid=20963315 file=module.nim:135
signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x105b40c8d?, 0x14000080900?})
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/panic.go:1047 +0x40 fp=0x14000062690 sp=0x14000062660 pc=0x105a03240
runtime.sigNotOnStack(0x10)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/signal_unix.go:1020 +0x5c fp=0x140000626b0 sp=0x14000062690 pc=0x105a19a2c
runtime.adjustSignalStack(0x10, 0x14000054000, 0x14000062758)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/signal_unix.go:581 +0x250 fp=0x14000062720 sp=0x140000626b0 pc=0x105a18d30
runtime.sigtrampgo(0x10, 0x140000628c0, 0x14000062928)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/signal_unix.go:469 +0x174 fp=0x140000627a0 sp=0x14000062720 pc=0x105a18984
runtime.sigtrampgo(0x10, 0x140000628c0, 0x14000062928)
        <autogenerated>:1 +0x1c fp=0x140000627d0 sp=0x140000627a0 pc=0x105a334bc
runtime.sigtramp()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/sys_darwin_arm64.s:227 +0x4c fp=0x14000062890 sp=0x140000627d0 pc=0x105a32a6c

goroutine 34 [syscall, locked to thread]:
runtime.goexit()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000063fe0 sp=0x14000063fe0 pc=0x105a31cb4

goroutine 17 [running, locked to thread]:
        goroutine running on other thread; stack unavailable

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:363 +0xe4 fp=0x14000050fa0 sp=0x14000050f80 pc=0x105a05b84
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:369
runtime.forcegchelper()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:302 +0xb4 fp=0x14000050fd0 sp=0x14000050fa0 pc=0x105a05a14
runtime.goexit()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000050fd0 sp=0x14000050fd0 pc=0x105a31cb4
created by runtime.init.6
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:290 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:363 +0xe4 fp=0x14000051770 sp=0x14000051750 pc=0x105a05b84
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgcsweep.go:278 +0xa4 fp=0x140000517b0 sp=0x14000051770 pc=0x1059f34e4
runtime.gcenable.func1()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgc.go:178 +0x28 fp=0x140000517d0 sp=0x140000517b0 pc=0x1059e7908
runtime.goexit()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000517d0 sp=0x140000517d0 pc=0x105a31cb4
created by runtime.gcenable
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgc.go:178 +0x70

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x14000024230?, 0x105b89870?, 0x1?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:363 +0xe4 fp=0x14000051f50 sp=0x14000051f30 pc=0x105a05b84
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x105cd6a80)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgcscavenge.go:389 +0x5c fp=0x14000051f80 sp=0x14000051f50 pc=0x1059f149c
runtime.bgscavenge(0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgcscavenge.go:617 +0x44 fp=0x14000051fb0 sp=0x14000051f80 pc=0x1059f1a34
runtime.gcenable.func2()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgc.go:179 +0x28 fp=0x14000051fd0 sp=0x14000051fb0 pc=0x1059e78a8
runtime.goexit()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000051fd0 sp=0x14000051fd0 pc=0x105a31cb4
created by runtime.gcenable
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mgc.go:179 +0xb4

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:363 +0xe4 fp=0x1400004c580 sp=0x1400004c560 pc=0x105a05b84
runtime.goparkunlock(...)
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/proc.go:369
runtime.runfinq()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mfinal.go:180 +0x128 fp=0x1400004c7d0 sp=0x1400004c580 pc=0x1059e6b28
runtime.goexit()
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400004c7d0 sp=0x1400004c7d0 pc=0x105a31cb4
created by runtime.createfing
        /opt/homebrew/Cellar/go/1.19.5/libexec/src/runtime/mfinal.go:157 +0x94
Traceback (most recent call last)
/Users/stefan/proj/status/status-desktop/src/nim_status_client.nim(197) nim_status_client
/Users/stefan/proj/status/status-desktop/src/nim_status_client.nim(194) mainProc
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/stefan/proj/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(567) onSlotCalled
/Users/stefan/proj/status/status-desktop/src/app_service/service/keychain/service.nim(67) onKeychainManagerSuccess
/Users/stefan/proj/status/status-desktop/src/app/core/eventemitter.nim(59) emit
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(147) :anonymous
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/io_interface.nim(186) keychainObtainedDataSuccess
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/module.nim(623) keychainObtainedDataSuccess
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(570) terminateCurrentFlow
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(442) cancelCurrentFlow
/Users/stefan/proj/status/status-desktop/src/app_service/service/keycard/service.nim(143) cancelCurrentFlow
/Users/stefan/proj/status/status-desktop/vendor/nim-keycard-go/keycard_go.nim(21) keycardCancelFlow
SIGABRT: Abnormal termination.
Traceback (most recent call last)
/Users/stefan/proj/status/status-desktop/src/nim_status_client.nim(197) nim_status_client
/Users/stefan/proj/status/status-desktop/src/nim_status_client.nim(194) mainProc
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/stefan/proj/status/status-desktop/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/stefan/proj/status/status-desktop/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(567) onSlotCalled
/Users/stefan/proj/status/status-desktop/src/app_service/service/keychain/service.nim(67) onKeychainManagerSuccess
/Users/stefan/proj/status/status-desktop/src/app/core/eventemitter.nim(59) emit
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(147) :anonymous
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/io_interface.nim(186) keychainObtainedDataSuccess
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/module.nim(623) keychainObtainedDataSuccess
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(570) terminateCurrentFlow
/Users/stefan/proj/status/status-desktop/src/app/modules/shared_modules/keycard_popup/controller.nim(442) cancelCurrentFlow
/Users/stefan/proj/status/status-desktop/src/app_service/service/keycard/service.nim(143) cancelCurrentFlow
/Users/stefan/proj/status/status-desktop/vendor/nim-keycard-go/keycard_go.nim(21) keycardCancelFlow
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [run-macos] Error 1
```

**Comment by anastasiyaig** [comment]
I saw this today when adding account to wallet:

enable wallet
enable biometircs
click add account
confirm action with fingerprint

```
Warning: qrc:/imports/shared/controls/TokenDelegate.qml:67: TypeError: Cannot read property 'enabledNetworkCurrencyBalance' of null (qrc:/imports/shared/controls/TokenDelegate.qml:67, )
ERR 2023-04-03 10:16:57.639+03:00 rpc response error                         topics="rpc" tid=9638655 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:16:57.639+03:00 error doing rpc request                    topics="rpc" tid=9638655 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:16:57.640+03:00 error fetchOwnedCollectiblesTaskArg:       tid=9638655 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:02.643+03:00 rpc response error                         topics="rpc" tid=9638658 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:02.644+03:00 error doing rpc request                    topics="rpc" tid=9638658 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:02.644+03:00 error fetchOwnedCollectiblesTaskArg:       tid=9638658 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.118+03:00 rpc response error                         topics="rpc" tid=9638654 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.144+03:00 error doing rpc request                    topics="rpc" tid=9638654 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.144+03:00 error fetchOwnedCollectiblesTaskArg:       tid=9638654 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.510+03:00 rpc response error                         topics="rpc" tid=9638656 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.510+03:00 error doing rpc request                    topics="rpc" tid=9638656 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.511+03:00 error fetchOwnedCollectiblesTaskArg:       tid=9638656 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.906+03:00 rpc response error                         topics="rpc" tid=9638659 file=core.nim:36 err="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.906+03:00 error doing rpc request                    topics="rpc" tid=9638659 file=core.nim:40 methodName=wallet_getOpenseaAssetsByOwnerWithCursor exception="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
ERR 2023-04-03 10:17:03.907+03:00 error fetchOwnedCollectiblesTaskArg:       tid=9638659 file=async_tasks.nim:21 errDesription="\nstatus-go error [methodName:wallet_getOpenseaAssetsByOwnerWithCursor, code:-32000, message:unsuccessful request: 403 Forbidden ]\n"
Traceback (most recent call last)
/Users/jenkins/workspace/status-desktop/platforms/macos/src/nim_status_client.nim(197) nim_status_client
/Users/jenkins/workspace/status-desktop/platforms/macos/src/nim_status_client.nim(194) mainProc
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(569) onSlotCalled
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app_service/service/wallet_account/service.nim(600) onAllTokensBuilt
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/core/eventemitter.nim(59) emit
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/modules/main/wallet_section/current_account/module.nim(88) :anonymous
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/modules/main/wallet_section/current_account/module.nim(190) onTokensRebuilt
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/modules/main/wallet_section/current_account/module.nim(116) setAssetsAndBalance
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app/modules/main/wallet_section/current_account/controller.nim(52) getCurrentCurrency
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app_service/service/wallet_account/service.nim(431) getCurrency
/Users/jenkins/workspace/status-desktop/platforms/macos/src/app_service/service/settings/service.nim(109) getCurrency
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimbus-build-system/vendor/Nim/lib/pure/strutils.nim(214) toUpperAscii
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimbus-build-system/vendor/Nim/lib/system/gc.nim(440) newObj
/Users/jenkins/workspace/status-desktop/platforms/macos/vendor/nimbus-build-system/vendor/Nim/lib/system/alloc.nim(783) rawAlloc
```
